### PR TITLE
Corrects encfsctl cat and add reverse cat

### LINKED ISSUE #173: Encrypt files with encfsctl (Reverse encfsctl cat)
In the same way that `encfsctl cat` works as a standalone tool to directly decrypt a file without mounting the volume, it would be useful to have a command to directly encrypt a file without needing to mount the volume.

### LINKED ISSUE #473: Is "encfsctl cat" broken ?
Hi,

I can't manage to make `encfsctl cat` work.

If I make :
`encfsctl cat /encfs/root/dir foo`
I get :
`ERROR decode err: Filename too small to decode`
`unable to open foo`

If I make :
`encfsctl cat /encfs/root/dir qsSJgvkgIoFIDPS5RxbBcC3r`
I get :
`unable to open qsSJgvkgIoFIDPS5RxbBcC3r`

Anything broken ?

Thank you 👍

### PR DESCRIPTION
**Pull request by benrubson**
Hi,

This solves and thus closes #473 and closes #173 👍 

Ben

### CODE REVIEW

**Comment by rfjakob** [comment]
Test case for --reverse please

**Comment by mouse07410** [comment]
I confirm that this patch works on MacOS 10.13.3.

**Comment by rfjakob** [comment]
Hmm, I'm getting the same build failure that Travis complains about:
```
/home/jakob/code/encfs/encfs/encfsctl.cpp: In function ‘encfs::RootPtr initRootInfo(int&, char**&)’:
/home/jakob/code/encfs/encfs/encfsctl.cpp:257:59: error: cannot convert ‘std::shared_ptr<encfs::EncFS_Context>’ to ‘encfs::EncFS_Context*’ for argument ‘1’ to ‘encfs::RootPtr encfs::initFS(encfs::EncFS_Context*, const std::shared_ptr<encfs::EncFS_Opts>&)’
     if (checkDir(opts->rootDir)) result = initFS(ctx, opts);
                                                           ^
/home/jakob/code/encfs/encfs/encfsctl.cpp: In function ‘encfs::RootPtr initRootInfo(const char*)’:
/home/jakob/code/encfs/encfs/encfsctl.cpp:278:30: error: cannot convert ‘std::shared_ptr<encfs::EncFS_Context>’ to ‘encfs::EncFS_Context*’ for argument ‘1’ to ‘encfs::RootPtr encfs::initFS(encfs::EncFS_Context*, const std::shared_ptr<encfs::EncFS_Opts>&)’
     result = initFS(ctx, opts);
                              ^
```

**Comment by benrubson** [comment]
OK, ready to merge 👍

**Comment by rfjakob** [comment]
Merged, thanks!
