### ISSUE TITLE
Compile time errors (fuse_dirh_t)

### ISSUE THREAD

**Issue by sergiopatino** [vgough/encfs#163]
I'm experiencing the following when trying to compile encfs from source.

In file included from /root/encfs/encfs/FSConfig.h:30:0,
                 from /root/encfs/encfs/BlockFileIO.h:26,
                 from /root/encfs/encfs/BlockFileIO.cpp:21:
/root/encfs/encfs/encfs.h:67:36: error: 'fuse_dirh_t' has not been declared
 int encfs_getdir(const char *path, fuse_dirh_t h, fuse_dirfil_t filler);
                                    ^
/root/encfs/encfs/encfs.h:67:51: error: 'fuse_dirfil_t' has not been declared
 int encfs_getdir(const char *path, fuse_dirh_t h, fuse_dirfil_t filler);
                                                   ^
CMakeFiles/encfs.dir/build.make:110: recipe for target 'CMakeFiles/encfs.dir/encfs/BlockFileIO.cpp.o' failed
make[2]: *** [CMakeFiles/encfs.dir/encfs/BlockFileIO.cpp.o] Error 1
CMakeFiles/Makefile2:2036: recipe for target 'CMakeFiles/encfs.dir/all' failed
make[1]: *** [CMakeFiles/encfs.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

Looking at libfuse it appears this functionality has been removed in the current source code but I can see it in the old google repository:

https://extf.googlecode.com/svn/trunk/VendorExtensions/S3/s3fs/include/fuse.h

/* Used by deprecated getdir() method */
typedef struct fuse_dirhandle *fuse_dirh_t;
typedef int (*fuse_dirfil_t) (fuse_dirh_t h, const char *name, int type,
                              ino_t ino);

Are their any plans to move away from this dependency?

**Comment by sergiopatino** [comment]
Some further digging. Looks like this was removed back in 2013.

https://github.com/libfuse/libfuse/commit/0e4c55c3fb0900e6ab54ea64edb5a6f371deebbc#diff-8714d0bd96c6c16268766f844020c4d4

**Comment by vgough** [comment]
Can you try building from the readdir branch (PR #164)?   It appears to work with FUSE 2.9.4, but that version also still has the deprecated getdir method defined, so you must have something more recent.
